create table if not exists navigator_course(
course_id integer not null,
course_name varchar(255) null,
course_types varchar(255) null,
filters varchar(255) null,
favourites varchar(255) null,
mandatory_learning_hrs integer null,
course_combinations varchar(255) null,
reference varchar(255) null,
ref_link_provided varchar(255) null,
reference_duration integer null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint navigator_course_pk primary key(course_id));